In [2]:
import numpy as np

In [3]:
w1,w2,w3=0.3,0.2,0.5

In [4]:
w2

0.2

In [5]:
kanto_temp=73
kanto_rainfall=67
kanto_humidity=43

In [6]:
kanto_yeild_apples=kanto_temp*w1+kanto_rainfall*w2+kanto_humidity*w3


In [8]:
kanto_yeild_apples

56.8

To make it slightly easier we create climate region as a vector i.e a list of numbers


They represent temp,rainfall,humidity


In [9]:
kanto=[73,67,43]
johto=[91,88,64]
hoenn=[87,143,58]
sinnoh=[102,43,57]
unova=[69,96,70]

In [10]:
weights=[w1,w2,w3]


We can now write a function crop_yeild to calculate yeild of apples,given climate data and respective weights

In [28]:
##time
def crop_yeild(region,weights):
    result=0
    for x,w in zip(region,weights):
        result += x*w
    return result    
    

In [12]:
crop_yeild(kanto,weights)

56.8

In [13]:
import numpy as np

In [14]:
kanto=np.array([w1,w2,w3])

In [15]:
kanto

array([0.3, 0.2, 0.5])

In [16]:
type(kanto)

numpy.ndarray

In [17]:
kanto[1]

0.2

In [18]:
kanto=np.array([73,67,43])

In [19]:
kanto

array([73, 67, 43])

In [21]:
weights=np.array([w1,w2,w3])


In [22]:
weights

array([0.3, 0.2, 0.5])

In [23]:
np.dot(weights,kanto)

56.8

In [25]:
np.dot(kanto,weights)

56.8

In [24]:
kanto*weights

array([21.9, 13.4, 21.5])

In [26]:
(kanto*weights).sum()

56.8

In [3]:
import numpy as np

Multi dimensional arrays



In [4]:
climate_data = np.array([[73,67,43],
                         [91,68,64],
                         [87,134,58],
                         [102,43,77],
                         [69,96,70]])

In [5]:
climate_data

array([[ 73,  67,  43],
       [ 91,  68,  64],
       [ 87, 134,  58],
       [102,  43,  77],
       [ 69,  96,  70]])

In [6]:
climate_data.shape

(5, 3)

In [8]:
climate_data.dtype

dtype('int32')

In [ ]:
w1,w2,w3=0.3,0.2,0.5

In [11]:
weights=np.array([w1,w2,w3])

NameError: name 'w1' is not defined

In [13]:
weights=np.array([w1,w2,w3])

NameError: name 'w1' is not defined

In [ ]:
w1,w2,w3=0.3,0.2,0.5

In [15]:
w2

NameError: name 'w2' is not defined

In [14]:
weights=np.array([w1,w2,w3])

NameError: name 'w1' is not defined

matmul is generally used for matrix multiplication

In [16]:
import urllib.request


In [17]:
urllib.request.urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv',
                          'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x276a94b0400>)

To read files into numoy array; we can use genfromtxt function

In [19]:
climate_data= np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

NameError: name 'genfromtxt' is not defined

In [20]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

delimiter is  used to represent what our data is seperated by:)

skip_header=1:it removes the first line that is header

In [22]:
climate_data.shape

(10000, 3)

@ can be used to get dot product of two matrices

We can now add a fourth column using np.concatenate function

We need to provide to axis arguement to np.concatenate to specify the dimension along with the concatenation should be performed

In [24]:
np.savetxt('climate_data.txt',climate_data,comments='')

In [25]:
arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([[2,2,3],[3,4,6]])


In [26]:
arr1==arr2

array([[False,  True,  True],
       [ True,  True, False]])

In [27]:
(arr1==arr2).sum()

4

In [30]:
climate_data[1:,0:1]

array([[39.],
       [59.],
       [84.],
       ...,
       [99.],
       [70.],
       [92.]])

In [32]:
##ALL zeros
np.zeros([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [33]:
##All ones
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
##Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
##Random vector
np.random.rand(5)

array([0.04314312, 0.36452975, 0.13894746, 0.40799944, 0.50492414])

Reading and writing from a python file

In [37]:
import os

In [38]:
os.getcwd()

'C:\\Users\\dell\\.vscode\\CODECC'

In [39]:
os.listdir()

['.ipynb_checkpoints',
 'ANALYSISWP.ipynb',
 'climate.txt',
 'climate_data.txt',
 'Untitled.ipynb']

You can create a new directory using os.makedirs

In [43]:
os.makedirs('./data',exist_ok=True)

In [44]:
'data' in os.listdir()

True

In [46]:
url1= 'https://hub.jovian.ml/wp-content/uploads/2020/08/loans1.txt'
url2= 'https://hub.jovian.ml/wp-content/uploads/2020/08/loans2.txt'
url3= 'https://hub.jovian.ml/wp-content/uploads/2020/08/loans3.txt'

In [45]:
import urllib.request

In [47]:
urllib.request.urlretrieve(url1,'./data/loans1.txt')

('./data/loans1.txt', <http.client.HTTPMessage at 0x276afbd25b0>)

In [48]:
urllib.request.urlretrieve(url2,'./data/loans2.txt')

('./data/loans2.txt', <http.client.HTTPMessage at 0x276afbd2850>)

In [49]:
urllib.request.urlretrieve(url3,'./data/loans3.txt')

('./data/loans3.txt', <http.client.HTTPMessage at 0x276afbd2af0>)

In [51]:
os.listdir('./data')

['loans1.txt', 'loans2.txt', 'loans3.txt']

Python files:


In [52]:
file1=open('./data/loans1.txt',mode ='r')

In [53]:
file1_contents=file1.read()

In [54]:
print(file1_contents)

amount,duration,rate,down_payment
100000,36,0.08,20000
200000,12,0.1,
628400,120,0.12,100000
4637400,240,0.06,
42900,90,0.07,8900
916000,16,0.13,
45230,48,0.08,4300
991360,99,0.08,
423000,27,0.09,47200


In [55]:
file1.close()

Once file is closed it can no longer be read

In [58]:
file1.read()

ValueError: I/O operation on closed file.

The same thing as above can be done with python's with operator

In [59]:
with open('./data/loans2.txt','r') as file2:
    file2_contents=file2.read()
    print(file2_contents)

amount,duration,rate,down_payment
828400,120,0.11,100000
4633400,240,0.06,
42900,90,0.08,8900
983000,16,0.14,
15230,48,0.07,4300



In [60]:
file2.read()

ValueError: I/O operation on closed file.

If you want to read files line by line:


In [61]:
with open('./data/loans3.txt','r') as file3:
    file3_line=file3.readlines()

In [62]:
file3_line

['amount,duration,rate,down_payment\n',
 '883000,16,0.14,\n',
 '45230,48,0.07,4300\n',
 '100000,12,0.1,\n',
 '728400,120,0.12,100000\n',
 '3637400,240,0.06,\n',
 '82900,90,0.07,8900\n',
 '316000,16,0.13,\n',
 '15230,48,0.08,4300\n',
 '991360,99,0.08,\n',
 '323000,27,0.09,4720010000,36,0.08,20000\n',
 '528400,120,0.11,100000\n',
 '8633400,240,0.06,\n',
 '12900,90,0.08,8900\n']

In [63]:
file3_line[2]

'45230,48,0.07,4300\n'

In [64]:
file3_line[1].strip()

'883000,16,0.14,'